In [1]:
import numpy as np

In [39]:
def print_list(L):
    index = 0
    for elem in L:
        print("--Element {}--".format(index))
        print(elem, "\n")
        index += 1

In [2]:
def next_permutation(L):
    n = len(L)
    i = n - 2
    while i >= 0 and L[i] >= L[i+1]:
        i -= 1

    if i == -1:
        return False
    j = i + 1
    while j < n and L[j] > L[i]:
        j += 1
    j -= 1
    L[i], L[j] = L[j], L[i]
    left = i + 1
    right = n - 1

    while left < right:
        L[left], L[right] = L[right], L[left]
        left += 1
        right -= 1

    return True

In [28]:
def check_square(mat):
    # Check rows
    got_sum = False
    ans = 0
    diag = 0
    for i in range(mat.shape[0]):
        diag += mat[i, i]
        if not got_sum:
            ans = mat[i, :].sum()
            got_sum = True
            continue
        if (ans != mat[i, :].sum() or ans != mat[:, i].sum()):
            return False
    return diag == ans

In [25]:
def get_magic_square(n, all=False):
    squares = []
    nums = list(np.linspace(1, n ** 2, n ** 2))
    while True:
        aux = np.resize(nums, (n, n))
        if check_square(aux):
            squares.append(aux)
            if not all:
                break
        if not next_permutation(nums):
            break

    return squares

In [40]:
print_list(get_magic_square(3, all=True))

--Element 0--
[[2. 4. 9.]
 [6. 8. 1.]
 [7. 3. 5.]] 

--Element 1--
[[2. 6. 7.]
 [4. 8. 3.]
 [9. 1. 5.]] 

--Element 2--
[[2. 7. 6.]
 [9. 5. 1.]
 [4. 3. 8.]] 

--Element 3--
[[2. 9. 4.]
 [7. 5. 3.]
 [6. 1. 8.]] 

--Element 4--
[[4. 2. 9.]
 [8. 6. 1.]
 [3. 7. 5.]] 

--Element 5--
[[4. 3. 8.]
 [9. 5. 1.]
 [2. 7. 6.]] 

--Element 6--
[[4. 8. 3.]
 [2. 6. 7.]
 [9. 1. 5.]] 

--Element 7--
[[4. 9. 2.]
 [3. 5. 7.]
 [8. 1. 6.]] 

--Element 8--
[[5. 1. 9.]
 [3. 8. 4.]
 [7. 6. 2.]] 

--Element 9--
[[5. 1. 9.]
 [7. 6. 2.]
 [3. 8. 4.]] 

--Element 10--
[[5. 3. 7.]
 [1. 8. 6.]
 [9. 4. 2.]] 

--Element 11--
[[5. 3. 7.]
 [9. 4. 2.]
 [1. 8. 6.]] 

--Element 12--
[[5. 7. 3.]
 [1. 6. 8.]
 [9. 2. 4.]] 

--Element 13--
[[5. 7. 3.]
 [9. 2. 4.]
 [1. 6. 8.]] 

--Element 14--
[[5. 9. 1.]
 [3. 4. 8.]
 [7. 2. 6.]] 

--Element 15--
[[5. 9. 1.]
 [7. 2. 6.]
 [3. 4. 8.]] 

--Element 16--
[[6. 1. 8.]
 [7. 5. 3.]
 [2. 9. 4.]] 

--Element 17--
[[6. 2. 7.]
 [8. 4. 3.]
 [1. 9. 5.]] 

--Element 18--
[[6. 7. 2.]
 [1. 5. 9.]